stickerIDList = ['CAACAgUAAxkBAAEBYsVfccjron2sngX2P_ESrzdMphqBsAACXgADIpOQBdu6gyOzY5faGwQ',
                'CAACAgUAAxkBAAEBYtRfcc58s4e4XkH7cUX87AFSgYLItQACXwADIpOQBZvGve4yh9uKGwQ',
                'CAACAgUAAxkBAAEBYtZfcc5_qKtfbazStr3mpWovfeCjNgACYAADIpOQBXhETHv-cczFGwQ',
                'CAACAgUAAxkBAAEBYthfcc6BdNfl_v8Pdw6fdpuf6A-ajAACYQADIpOQBT9bCq9JxwmsGwQ',
                'CAACAgUAAxkBAAEBYtpfcc7mMEy0EsUGjKyTfcXTJc_FqgACYgADIpOQBd-Ld4RQMiasGwQ',
                'CAACAgUAAxkBAAEBYtxfcc8GuIHF03SfKCb14IUI_S1qiwACYwADIpOQBVyzzNu3OdOvGwQ',
                'CAACAgUAAxkBAAEBYt5fcc8RpHh9kmuxXMJKOkQSYBHL-wACZAADIpOQBV3cXZwXEJeWGwQ',
                'CAACAgUAAxkBAAEBYuBfcc8TDQ_M2P6hG2iWCNSJ353BqwACZQADIpOQBVhMK5vv0Mv2GwQ',
                'CAACAgUAAxkBAAEBYuJfcc8saEGh0I3asnrjQqmI0-d0rAACZgADIpOQBVA-n-qeTLqsGwQ',
                'CAACAgUAAxkBAAEBYuRfcc8tp9Mn0rFYas4ilgABnqb6wNAAAmcAAyKTkAX1IFpS6DWjXxsE',
                'CAACAgUAAxkBAAEBYuVfcc8uVvZ2hOH1g2FNC4JokNnvzQACaAADIpOQBRO2dMwgHtjrGwQ',
                'CAACAgUAAxkBAAEBYudfcc8wFlRKnXBWaJ54TDOk0C8TcQACaQADIpOQBePWXS2eVVdlGwQ',
                'CAACAgUAAxkBAAEBYupfcc9TMTRRa4M6wU_mMxHgVuvyvgACagADIpOQBQ6oDiceO1y7GwQ',
                'CAACAgUAAxkBAAEBYutfcc9UCT9GqOVbGrdjPIq2k1NW4QACawADIpOQBSb1QFrF36fSGwQ',
                'CAACAgUAAxkBAAEBYu5fcc9Wrf5MUWmo2PeEJa_0CJ0ooAACbAADIpOQBVxBkTksrLtKGwQ',
                'CAACAgUAAxkBAAEBYu9fcc9XyVwrXoZCEe7WywQ7aJsp_wACbQADIpOQBbXg8nB9BEi7GwQ',
                'CAACAgUAAxkBAAEBYvJfcc9aETTaj184u8qEJgaOwqgk0gACbgADIpOQBUKWnVklaITwGwQ',
                'CAACAgUAAxkBAAEBYvNfcc9bp_y8PcPyCssK6iJPK2pdDgACbwADIpOQBYO8AZOcNHf7GwQ',
                'CAACAgUAAxkBAAEBYvRfcc9b-oR3A2Hg5Im5f8gEx64g6QACcAADIpOQBbSeEI2LV4OkGwQ',
                'CAACAgUAAxkBAAEBYvVfcc9bXLmpO4hzmqSvkFTq94hP9AACcQADIpOQBd5i00GdU8XtGwQ',
                'CAACAgUAAxkBAAEBYvpfcc9gFzNuMwUiha5PiX4m--7iUgACcgADIpOQBRzDuCD-tZlTGwQ',
                'CAACAgUAAxkBAAEBYvtfcc9gOE_U36UbrducqkeQbJ0_3AACcwADIpOQBUpq93J6F0nKGwQ',
                'CAACAgUAAxkBAAEBYx9fceX5_sEWpP2GsanW74fI9i7LowACdAADIpOQBXCXEW0IVoeWGwQ',
                'CAACAgUAAxkBAAEBYyBfceX5wmeir5tlM4kPVHEJCKNgBgACdQADIpOQBT1Vl8zfuKyJGwQ',
                'CAACAgUAAxkBAAEBYyFfceX50EPvnJlw-nSuNQzmjWUPUQACdgADIpOQBaFwgf330ElkGwQ',
                'CAACAgUAAxkBAAEBYyJfceX5Ci4aBcYPKy1qzYAG8CNBewACdwADIpOQBSi6GWxtFhbPGwQ',
                'CAACAgUAAxkBAAEBYyNfceX53IQZc449BvfkubhPixddsgACeAADIpOQBTiugkY3UR-fGwQ',
                'CAACAgUAAxkBAAEBYyRfceX5PugkEeRykS_oPAisLbJ5fwACeQADIpOQBWJ68-R1EAjbGwQ',
                'CAACAgUAAxkBAAEBYyVfceX5e6vG9jVeB7DmGChwS6uk_QACegADIpOQBRb70o2tKH3sGwQ',
                'CAACAgUAAxkBAAEBYyZfceX5XAUrUKHaOEhg5Bn_kSfzggACewADIpOQBdeX4U3S_aQWGwQ',
                'CAACAgUAAxkBAAEBYydfceX5P064Y4VQGEMcA_yKHyoY2wACfAADIpOQBZBotoZnDzCzGwQ',
                'CAACAgUAAxkBAAEBYyhfceX5bfKoNewiAAG9Plf9VRwlDhMAAn0AAyKTkAXT6jQOc6cfsBs',
                'CAACAgUAAxkBAAEBYzNfcegIBo9kuGE2Dlbit6E1W0QgDAACfgADIpOQBdcFZOmz-0wkGwQ',
                ]

samQuotesList = ["Why are you like this?", 
                 "I'm an idiot sandwich!", 
                 "I can't believe you've done this!", 
                 "It do be like that sometimes.", 
                 "It's time to stop.", 
                 "Where are your parents??", 
                 "Who invented Python?", 
                 "Who invented math?", 
                 "Who invented integration?", 
                 "Fuck you", 
                 "Why are you here?",
                 "Go home!"]

radioList = ["https://youtu.be/NoWudgNNIwM", # mongolian throat singing
             "https://youtu.be/Mh5LY4Mz15o", # history of japan
             "https://youtu.be/xuCn8ux2gbs", # history of the world
             "https://youtu.be/tVj0ZTS4WF4", # russian singer
             "https://youtu.be/7CawoPNkY00", # asian music video
             "https://youtu.be/-Yvh6hWDBzA", # ali's cheena agogo
             "https://youtu.be/W8x4m-qpmJ8", # xue hua piao piao
             "https://youtu.be/fLr0-gDOaMY", # pink guy stfu
            ]

ballList = ["Yes.",
            "It is certain.",
            "It is decidedly so.",
            "Without a doubt.",
            "Yes, definitely.",
            "You may rely on it.",
            "As I see it, yes.",
            "Most likely.",
            "Outlook: good.",
            "Signs point to yes.",
            "Of course, my horse.",
            "No.",
            "Reply hazy try again.",
            "Ask again later.",
            "Better not tell you now.",
            "Cannot predict now.",
            "Concentrate and ask again.",
            "Don't count on it.",
            "My reply is no.",
            "My sources say no.",
            "Outlook: not so good.",
            "Very doubtful.",
            "There is a time and place for everything, but not now.",
            ]

slapList = ['VICTIM was shot by VICTOR.',
            'VICTIM was pricked to death.',
            'VICTIM walked into a cactus while trying to escape VICTOR.',
            'VICTIM drowned.',
            'VICTIM drowned whilst trying to escape VICTOR.',
            'VICTIM blew up.',
            'VICTIM was blown up by VICTOR.',
            'VICTIM hit the ground too hard.',
            'VICTIM fell from a high place.',
            'VICTIM fell off a ladder.',
            'VICTIM fell into a patch of cacti.',
            'VICTIM was doomed to fall by VICTOR.',
            'VICTIM was blown from a high place by VICTOR.',
            'VICTIM was squashed by a falling anvil.',
            'VICTIM went up in flames.',
            'VICTIM burned to death.',
            'VICTIM was burnt to a crisp whilst fighting VICTOR.',
            'VICTIM walked into a fire whilst fighting VICTOR.',
            'VICTIM tried to swim in lava.',
            'VICTIM tried to swim in lava while trying to escape VICTOR.',
            'VICTIM was struck by lightning.',
            'VICTIM was slain by VICTOR.',
            'VICTIM got finished off by VICTOR.',
            'VICTIM was killed by magic.',
            'VICTIM was killed by VICTOR using magic.',
            'VICTIM starved to death.',
            'VICTIM suffocated in a wall.',
            'VICTIM fell out of the world.',
            'VICTIM was knocked into the void by VICTOR.',
            'VICTIM withered away.',
            'VICTIM was pummeled by VICTOR.',
            'VICTIM was fragged by VICTOR.',
            'VICTIM was desynchronized.',
            'VICTIM was wasted.',
            'VICTIM was busted.',
            'VICTIM\'s bones are scraped clean by the desolate wind.',
            'VICTIM has died of dysentery.',
            'VICTIM fainted.',
            'VICTIM is out of usable Pokemon! VICTIM whited out!',
            'VICTIM is out of usable Pokemon! VICTIM blacked out!',
            'VICTIM whited out!',
            'VICTIM blacked out!',
            'VICTIM says goodbye to this cruel world.',
            'VICTIM got rekt.',
            'VICTIM was sawn in half by VICTOR.',
            'VICTIM died. I blame VICTOR.',
            'VICTIM was axe-murdered by VICTOR.',
            'VICTIM\'s melon was split by VICTOR.',
            'VICTIM was sliced and diced by VICTOR.',
            'VICTIM was split from crotch to sternum by VICTOR.',
            'VICTIM\'s death put another notch in VICTOR\'s axe.',
            'VICTIM died impossibly!',
            'VICTIM died from VICTOR\'s mysterious tropical disease.',
            'VICTIM escaped infection by dying.',
            'VICTIM played hot-potato with a grenade.',
            'VICTIM was knifed by VICTOR.',
            'VICTIM fell on his sword.',
            'VICTIM ate a grenade.',
            'VICTIM practiced being VICTOR\'s clay pigeon.',
            'VICTIM is what\'s for dinner!',
            'VICTIM was terminated by VICTOR.',
            'VICTIM was shot before being thrown out of a plane.',
            'VICTIM was not invincible.',
            'VICTIM has encountered an error.',
            'VICTIM died and reincarnated as a goat.',
            'VICTOR threw VICTIM off a building.',
            'VICTIM is sleeping with the fishes.',
            'VICTIM got a premature burial.',
            'VICTOR replaced all of VICTIM\'s music with Nickelback.',
            'VICTOR spammed VICTIM\'s email.',
            'VICTOR made VICTIM a knuckle sandwich.',
            'VICTOR slapped VICTIM with pure nothing.',
            'VICTOR hit VICTIM with a small, interstellar spaceship.',
            'VICTIM was quickscoped by VICTOR.',
            'VICTOR put VICTIM in check-mate.',
            'VICTOR RSA-encrypted VICTIM and deleted the private key.',
            'VICTOR put VICTIM in the friendzone.',
            'VICTOR slaps VICTIM with a DMCA takedown request!',
            'VICTIM became a corpse blanket for VICTOR.',
            'Death is when the monsters get you. Death comes for VICTIM.',
            'Cowards die many times before their death. VICTIM never tasted death but once.',
            'VICTIM died of hospital gangrene.',
            'VICTIM got a house call from Doctor VICTOR.',
            'VICTOR beheaded VICTIM.',
            'VICTIM got stoned...by an angry mob.',
            'VICTOR sued the pants off VICTIM.',
            'VICTIM was impeached.',
            'VICTIM was one-hit KO\'d by VICTOR.',
            'VICTOR sent VICTIM to /dev/null.',
            'VICTOR sent VICTIM down the memory hole.',
            'VICTIM was a mistake.',
            '"VICTIM was a mistake." - VICTOR',
            'VICTOR checkmated VICTIM in two moves.',
            'VICTIM was made redundant.',
            'VICTIM was assimilated.',
            'VICTIM is with Harambe now.',
            ]